shop/urls.py
from django.contrib import admin
from django.urls import path
from shop_main.views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name = 'main'),
    path('index/',index, name = 'main'),
    path('product/<product_slug>/',product, name = 'product'),
    path('category/<category_slug>/',category, name = 'category'),
    
    ##
    path('cart/',cart, name = 'cart'),
    path('add/<product_slug>/',add_to_cart, name = 'add'),
    path('increase/<product_slug>/',increase_item, name = 'increase'),
    path('remove/<product_slug>/',remove_from_cart, name = 'remove'),
    path('decrease/<product_slug>/',decrease_item, name = 'decrease'),
    
    ##
    path('login/',login, name = 'login'),
    path('logout/',logout, name = 'logout'),
    path('registration/',registration, name = 'registration'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_main/models.py
from django.db import models
from django.urls import reverse
from django.db.models import F
import os

# Create your models here.
class Test(models.Model):
    title = models.CharField(max_length=30)
    text = models.CharField(max_length=300)
    picture = models.ImageField(upload_to ='media/')



class Category(models.Model):
    name = models.CharField(max_length=30, unique = True)
    slug = models.SlugField()

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category', kwargs = {'category_slug':self.slug})


class Brand(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

def image_folder(instance,filename):
    return '{0}/{1}'.format(instance.slug,filename)

class Product(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField(max_length=300)
    picture = models.ImageField(upload_to=image_folder)
    category = models.ForeignKey(Category, to_field='name', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=9, decimal_places=2,default = 0.00)
    available = models.BooleanField(default = True)
    slug = models.SlugField()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product', kwargs = {'product_slug':self.slug})


            
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField(default = 1)
    cost = models.DecimalField(max_digits=9, decimal_places=2,default = 0.00)
    total = models.DecimalField(max_digits=9, decimal_places=2,default = 0.00)

    def save(self, *args, **kwargs):
        self.cost = self.product.cost
        self.total = self.quantity * self.cost
        super().save(*args, **kwargs)
    
    def __str__(self):
        return str(self.product)

class PromoCode(models.Model):
    code = models.CharField(max_length=30,)
    title = models.CharField(max_length=30,)
    total = models.DecimalField(max_digits=9, decimal_places=2,default = 0.00)
    
class Cart(models.Model):
    products = models.ManyToManyField(CartItem)
    promocodes = models.ManyToManyField(PromoCode)
    total = models.DecimalField(max_digits=9, decimal_places=2,default = 0.00)

    def get_products(self):
        return "\n".join([str(p.product) for p in self.products.all()])

    def __unicode__(self):
        return str(self.id)

shop_main/forms.py
from django import forms
 
class PromocodeForm(forms.Form):
    code = forms.CharField()

shop_main/views.py
from django.shortcuts import render
from decimal import Decimal
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from .forms import *

def index(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id = cart_id)
        request.session['total'] = cart.products.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        cart_id = request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id = cart_id)
   
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories':categories,
        'products':products,
        'cart':cart
    }
    return render(request,'base.html',context)

def product(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id = cart_id)
        request.session['total'] = cart.products.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        cart_id = request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id = cart_id)
    
    product = Product.objects.get(slug = product_slug) 
    context = {
        'cart':cart,
        'product':product
    }
    return render(request,'product.html',context)

def category(request, category_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id = cart_id)
        request.session['total'] = cart.products.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        cart_id = request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id = cart_id)
    category = Category.objects.get(slug = category_slug)
    context = {
        'cart':cart,
        'category':category
    }
    return render(request,'category.html',context)

def cart(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id = cart_id)
        request.session['total'] = cart.products.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        cart_id = request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id = cart_id)
    cart_items = CartItem.objects.all()
    for item in cart_items:
        cart.total +=item.total
    form = PromocodeForm

    if request.method == "POST":
        code = request.POST.get("code")
        promocode = PromoCode.objects.filter(title = code)
    else:
        promocode = PromoCode.objects.filter(title = 'Null')
    for code in promocode:
        cart.total-= code.total
    cart.save 
    context = {
        'form': form,
        'cart': cart,
        'promocode':promocode
    }
    return render(request,'cart.html',context)

def add_to_cart(self,product_slug):
    product = Product.objects.get(slug=product_slug)
    item,_ = CartItem.objects.get_or_create(product = product,total = product.cost)
    cart  = Cart.objects.first()
    if item not in cart.products.all():
        cart.products.add(item)
        item.quantity = 1 
        item.save()
        cart.save()
        return HttpResponseRedirect('/')

def increase_item(self,product_slug):
    product = Product.objects.get(slug=product_slug)
    cart  = Cart.objects.first()
    item = cart.products.get(product = product)
    item.quantity += 1
    item.save()
    return HttpResponseRedirect('/cart/')

def remove_from_cart(self,product_slug):
    product = Product.objects.get(slug=product_slug)
    cart  = Cart.objects.first()
    item = cart.products.get(product = product)
    item.delete()
    cart.save()
    return HttpResponseRedirect('/cart/')

def decrease_item(self,product_slug):
    product = Product.objects.get(slug=product_slug)
    cart  = Cart.objects.first()
    item = cart.products.get(product = product)
    item.quantity -= 1
    cart.total -= item.total
    if cart.total < 0:
        cart.total = 0
    if item.quantity <1:
        item.delete()
    item.save()
    cart.save()
    return HttpResponseRedirect('/cart/')




##
def login(request):
    test = Test.objects.all()
    context = {'test': test}
    return render(request,'login.html',context)

def logout(request):
    test = Test.objects.all()
    context = {'test': test}
    return render(request,'base.html',context)

def registration(request):
    test = Test.objects.all()
    context = {'test': test}
    return render(request,'base.html',context)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="{% static '/css/open-iconic.css'%}" rel="stylesheet">
</head>

<body>
{% block header %}  
  <header class=" p-4 ">
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <a class="navbar-brand" href="/">Еmarket</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarCollapse" style="">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Каталог <span class="sr-only">(current)</span></a>
        </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Акции <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2"type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 mr-sm-2" type="submit" width="100%">Search</button>
      </form>
      <form class="form-inline mt-2 mt-md-0" action="/login">
          <button class="btn btn-outline-primary mr-sm-2 w-100 " type="submit">  Вход </button>
      </form>
      <form class="form-inline mt-2 mt-md-0" action="/cart">
      <button class="btn btn-outline-success  mr-sm-2 w-100" type="submit"> Корзина <span class="badge badge-success badge-pill">{{cart.products.count}}</span></button>
      </form>
      
    </div>
  </nav>
  </header>
{% endblock header %}
<br>
{% block content %}
  <br><div class="container">
  <section id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-60" src="{% static '/icons/c.png'%}" alt="Первый слайд">
    </div>
    <div class="carousel-item">
      <img class="d-block w-60" src="{% static '/icons/c.png'%}" alt="Второй слайд">
    </div>
    <div class="carousel-item">
      <img class="d-block w-55" src="{% static '/icons/c.png'%}" alt="Третий слайд">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a> <br>
</section>
    <section class="row"> 
      {% for product in products %}
      <div class="col-sm" >
        <h4 align="">{{product.title}}</h4>
        <img class="img-fluid" width="255" src="{{Media}}{{product.picture.url}}" alt="" >
        <p>{{product.category}} {{product.brand}}  <span  class="mt-2 h5 text-warning">{{product.cost}}р </span>
        <div class="btn-group">
          <a class="btn  btn-outline-primary"  href="{{product.get_absolute_url}}" role="button">&nbsp;&nbsp;&nbsp;Подробнее&nbsp;&nbsp;</a> 
          <a class="btn  btn-outline-primary"  href="{%url 'add' product_slug=product.slug %}" role="button">&nbsp;&nbsp;&nbsp;В Корзину&nbsp;&nbsp;&nbsp;</a>
        </div>
      </div>
      {% endfor %}
    </section>
    </div>
{% endblock content %}

{% block footer %}
  <footer class="pt-2 my-md-4 pt-md-2 border-top"> </footer>
{% endblock footer %}
 
</div>
</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Корзина</span>
            <span class="badge badge-secondary badge-pill">{{cart.products.count}}</span>
          </h4>
          <ul class="list-group mb-3">
          {%for product in cart.products.all%}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{product.product.title}}</h6>
                <small class="text-muted">
                  <a class="badge" href="{%url 'increase' product_slug=product.product.slug %}" role="button">+ </a>
                  {{product.quantity}} 
                  <a class="badge" href="{%url 'decrease' product_slug=product.product.slug %}"> - </a>
                  <a class="badge badge-danger" href="{%url 'remove' product_slug=product.product.slug %}"> удалить</a>
                </small>
              </div>
              <span class="text-muted"> {{product.total}}</span>
            </li>
          {% endfor %}
          {% for code in promocode%}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Промокод</h6>
                <small>{{code.title}}</small>
              </div>
              <span class="text-success">{{code.total}}</span>
            </li>
          {%endfor %}  
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (RU)</span>
              <strong>{{cart.total}}</strong>
            </li>
          </ul>
          <form class="card p-2" method = "post" >
            {% csrf_token %}
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code"id="id_code" name = "code" >
              <div class="input-group-append">
                <button type="submit" class="btn btn-secondary">Ввести</button>
              </div>
            </div>
          </form>
        </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Адрес доставки</h4>
          <form class="needs-validation" novalidate="">
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">Имя</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                <div class="invalid-feedback">
                  Поле имя обязательно.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Фамилия</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                <div class="invalid-feedback">
                  Поле фамилия обязательно
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">@</span>
                </div>
                <input type="text" class="form-control" id="email" placeholder="you@example.com" required="">
                <div class="invalid-feedback" style="width: 100%;">
                  Поле email обязательно, введите его для отслеживания доставки.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Адрес</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <label for="country">Страна</label>
                <select class="custom-select d-block w-100" id="country" required="">
                  <option value="">Выбрать</option>
                  <option>Россия</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">Регион</label>
                <select class="custom-select d-block w-100" id="state" required="">
                  <option value="">Выбрать</option>
                  <option>Кемеровская область</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="zip">Индекс</label>
                <input type="text" class="form-control" id="zip" placeholder="" required="">
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Сохранить эту информацию для последующих операций</label>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Оплата</h4>
            <script src="https://api.fondy.eu/static_common/v1/checkout/ipsp.js"></script>
            <script>
            function checkoutInit(url) {
              $ipsp('checkout').scope(function() {
                this.setCheckoutWrapper('#checkout_wrapper');
                this.addCallback(__DEFAULTCALLBACK__);
                this.action('show', function(data) {
                  $('#checkout_loader').remove();
                  $('#checkout').show();
                });
                this.action('hide', function(data) {
                  $('#checkout').hide();
                });
                this.action('resize', function(data) {
                  $('#checkout_wrapper').width(800).height(data.height);
                });
                this.loadUrl(url);
              });
            };
            var button = $ipsp.get("button");
            button.setMerchantId(1396424);
            button.setAmount({{cart.total}}, 'RUB', true);
            button.setHost('api.fondy.eu');
            checkoutInit(button.getUrl());
            </script>

            <div id="checkout">
              <div id="checkout_wrapper"></div>
            </div>
        </div>
      </div>
{% endblock content %}

{%block footer%}
 <footer class="my-5 pt-5 text-muted text-center text-small"> </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';

        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');

          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
{%endblock footer%}

templates/login.html
{% extends "base.html" %}
{% block header %}
{% endblock header %}
{% block content %}
<section class="text-center">
 <div class="container my-0 col-lg-20 col-6 col-md-4 block"">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
  <label for="inputPassword" class="sr-only">Password</label>
  <br><input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
  <br><label><input type="checkbox" value="remember-me"> Remember me</label> 
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </div>
</section>
{% endblock content %}

{% block footer %}

{% endblock footer %}

templates/product.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
    <br><div class="col-md-12">
      <div class="card flex-md-row mb-4 shadow-sm h-md-10">
        <div class="card-body d-flex flex-column align-products-start">
        <img class="card-img flex-auto d-auto d-lg-block img-fluid"  src="{{Media}}{{product.picture.url}}">
        </div>
        <div class="card-body d-flex flex-column align-products-start">
          <h3 class="mb-0">
            <a class="text-dark">{{product.title}}</a>
          </h3>
          <div class="mb-1 text-muted">{{product.category}} ds {{product.brand}}</div>
          <p class="card-text mb-auto">{{product.text}}</p>
          <p class="mt-2 h3 text-warning"> {{product.cost}}р</p>
          <a class="btn  btn-outline-primary" href="{%url 'add' product_slug=product.slug %}" role="button">Добавить в корзину </a>
        </div>
      </div>
    </div>
    </div>
{% endblock content %}